# Generated by Django 3.2.23 on 2024-01-25 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('total_price', models.IntegerField(null=True)),
                ('qty', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(max_length=100, null=True)),
                ('razorpay_signature', models.CharField(max_length=100, null=True)),
                ('payment_status', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicemaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
